subgraphs:
  query:
    routing_url: http://localhost:4001
    schema:
      file: ../subgraphs/query-subgraph/schema.graphql
  mutation:
    routing_url: http://localhost:4002
    schema:
      file: ../subgraphs/mutation-subgraph/schema.graphql